new class Race
Evilkoy/Racing_Mx pull request #8
Opened 2022-08-16 14:30 UTC by Evilkoy

2022-08-16 17:05 UTC, maxxa1234 requested changes

2022-08-16 17:05 UTC, maxxa1234 commented on src/Race.java
> +        System.out.println("Your reward: " + (3000 + (3000 / pos)) + "$");
We can make separate var for  3000 + (3000 / pos) because it uses more than one time

2022-08-16 17:05 UTC, maxxa1234 commented on src/Race.java
> +        }
What if there will be a few equal places like 1.42, 1.95, 0,45

2022-08-21 07:01 UTC, maxxa1234 requested changes

2022-08-21 07:01 UTC, maxxa1234 commented on Racing_Mx.iml
> +  <component name="NewModuleRootManager" LANGUAGE_LEVEL="JDK_17" inherit-compiler-output="true">
What is it?

2022-08-21 07:01 UTC, maxxa1234 commented on src/META-INF/MANIFEST.MF
> +
what is it?

2022-08-21 07:01 UTC, maxxa1234 commented on src/UpgradeShop.java
>          }
What  if i == 7?

2022-08-21 13:20 UTC, Evilkoy commented on src/UpgradeShop.java
>          }
![image](https://user-images.githubusercontent.com/110408976/185792831-64c77e95-07a7-4f8b-90e0-f9257b28457f.png)

2022-09-07 18:11 UTC, closed without merging